# Generated by Django 5.2.14 on 2026-05-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("autor", models.CharField(max_length=100)),
                ("calorias", models.CharField(default="0 kcal", max_length=20)),
                ("proteinas", models.CharField(default="0 g", max_length=20)),
                ("carbohidratos", models.CharField(default="0 g", max_length=20)),
                ("azucares", models.CharField(default="0 g", max_length=20)),
                ("sodio", models.CharField(default="0 mg", max_length=20)),
                ("vitaminas", models.CharField(default="Ninguna", max_length=150)),
            ],
        ),
    ]
