# Generated by Django 5.2.14 on 2026-05-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="azucares",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="calorias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="carbohidratos",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="proteinas",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="sodio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="vitaminas",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
